# sudo: false
language: haskell
ghc:
    - 7.10.2
    - 7.10.1
    - 7.8.4
    - 7.6.3
    - 7.4.2
script:
        - cabal configure --enable-tests
        - cabal build
        - cabal test
install: cabal install -j
notifications:
  email: true
